### PR TITLE
Added Google Authentication 

### LINKED ISSUE #96: I will Add Google authentication
PLease Assign this task to me @riturajjain2000

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
## Explanation

I have successfully established Google Authentication .
and fixed issue number #96 

## Type of Change:

- Code

## Checklist

- [x] The PR title starts with "Fix #96 : "followed by a short, clear summary of the changes. ( If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...")
- [x] The PR explanation includes the words "Fixes #96 : ..." ( or "Fixes part of #bugnum" if the PR only partially fixes an issue ).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adhere to the contributing guidelines of the project.
- [x] The PR is raised for an issue that has been assigned to you.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is raised from a branch that is up-to-date with "develop".

### CODE REVIEW

**Comment by Abh1shekSingh** [comment]
Please Review the PR.

**Comment by Abh1shekSingh** [comment]
@riturajjain2000 Once this get approved then only it will be possible to work on other issue for me. Please review

**Review by riturajjain2000 — APPROVED** [review]

**Comment by riturajjain2000** [comment]
This PR broke the explore page , also the buttons for google and GitHub needs to be fixed , they beacame blue in color 
Screenshot 2022-04-28 162547

**Comment by Abh1shekSingh** [comment]
> This PR broke the explore page , also the buttons for google and GitHub needs to be fixed , they beacame blue in color Screenshot 2022-04-28 162547

The PR doesn't broke the explore page bro. First you need to login. Once you get logged in, then you can see the explore page. I added this functionality. I will make button responsive no worries.

**Comment by riturajjain2000** [comment]
Ok , so revert back , we don't want users to login first , not for the explore page at least , also after clicking on the sign-in buttons , the google account dialog should open , to choose from different account , which is also not happening

**Comment by Abh1shekSingh** [comment]
> Ok , so revert back , we don't want users to login first , not for the explore page at least , also after clicking on the sign-in buttons , the google account dialog should open , to choose from different account , which is also not happening

Okay

**Pull request merged**
