### PR TITLE
Added Jobhunt Page

### LINKED ISSUE #102: Create Jobhunt Page
Create a new page as Jobhunt with data from PORTAL.json from https://github.com/CSwala/awesome-career-pages.
The look and feel will be similar to explore page, with the company name as the tile title and upon clicking a tile, the link to the career page should open in a new tab!

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
## Explanation

I have Created New page and attached it with main page. 

## Type of Change:

- Code
- Quality Assurance

## Checklist
- [x] The PR title starts with "Fix #102: "followed by a short, clear summary of the changes. ( If this PR fixes part of an issue, prefix the title with "Fix part of #102: ...")
- [x] The PR explanation includes the words "Fixes #102: ..." ( or "Fixes part of #102" if the PR only partially fixes an issue ).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adhere to the contributing guidelines of the project.
- [x] The PR is raised for an issue that has been assigned to you.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is raised from a branch that is up-to-date with "develop".

### CODE REVIEW

**Comment by Abh1shekSingh** [comment]
@riturajjain2000   PLease Review I have added Jobhunt Page. But didnt added search facility. I will do that

**Comment by Abh1shekSingh** [comment]
@riturajjain2000  I have made the job hunt page. But currently i am not getting the logic in my head to make search and filter functionality. Later i will add that too. I have already worked with such functionality. but now i am not getting what to do.

**Comment by Abh1shekSingh** [comment]
I have added Search Functioanlity. But the problem with that is , once data is filtered and then later we empty our text from search field. we dont get the state back . we dont get the whole data back

**Comment by riturajjain2000** [comment]
> I have added Search Functioanlity. But the problem with that is , once data is filtered and then later we empty our text from search field. we dont get the state back . we dont get the whole data back

update me when its done

**Comment by Abh1shekSingh** [comment]
@riturajjain2000 I am not getting how to do thta, i am confused. Please give the marks for the page I made. filtered Nhi bn raha mere se

**Comment by riturajjain2000** [comment]
Alright, means this pr has functional job hunt page without a filter , right ??

**Comment by Abh1shekSingh** [comment]
Absolutely SIR. Sorry dont know why this happening to me. Mind is exhausted

**Review by riturajjain2000 — APPROVED** [review]

**Pull request merged**
