### PR TITLE
added GitHub Authentication

### LINKED ISSUE #69: authentication with github
Please assign this task to me

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
## Explanation

Added GitHub Authentication 

## Type of Change:

- Code
- Quality Assurance
- User Interface

## Checklist

- [x] The PR title starts with "Fix #69 : "followed by a short, clear summary of the changes. ( If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...")
- [x] The PR explanation includes the words "Fixes #69 : ..." ( or "Fixes part of #bugnum" if the PR only partially fixes an issue ).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adhere to the contributing guidelines of the project.
- [x] The PR is raised for an issue that has been assigned to you.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is raised from a branch that is up-to-date with "develop".

## ScreenShots
github1
github2
github3
github4

### CODE REVIEW

**Comment by Abh1shekSingh** [comment]
@riturajjain2000 Please Review my PR

**Comment by riturajjain2000** [comment]
can you send ss for the same

**Comment by Abh1shekSingh** [comment]
@riturajjain2000  I have added the screenshots.
You might be trying to login but it wouldn't worked for you I guess. That's actually because, I have to change the Callback URL to **cswala.in** as I was working locally, so I set that up as **localhost:3000**. I will change it now.

**Comment by riturajjain2000** [comment]
notify me when the final PR is ready

**Comment by Abh1shekSingh** [comment]
@riturajjain2000 I have done The final touch up. You can merge now.

**Review by riturajjain2000 — APPROVED** [review]

**Pull request merged**
